[package]
name = "shared-cfg-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "0.51.0"
aws-sdk-ecs = "0.21.0"
tokio = { version = "1", features = ["full"] }
log = "0.4.0"
env_logger = "0.9.0"
